### ISSUE TITLE
Corrupted outline out of sync between iPhone and Mac

### ISSUE THREAD

**Issue by valleydali** [vincode-io/Zavala#224] opened 2024-02-22 02:30 UTC
I have an outline which I created on my iPhone. When I open it on my Mac, I get this alert:

<img width="259" alt="Screenshot 2024-02-19 at 11 47 38 AM" src="https://github.com/vincode-io/Zavala/assets/37566098/54cd45d6-7264-4d1f-b58b-a8b925988eff">

If I click "Fix It", then all seems well at first. But the next time I go to open up the outline back on my iPhone, I get a similar alert with the same message, but this time on my iPhone. If I "fix" it there, then when I go back to my Mac, I get the alert again.

So, neither my iPhone nor my Mac like the way the other "fixes" things. As things stand, there is no way I can share an uncorrupted version of this outline between the two devices.

What happened here?

(I imagine that I can work around this by "fixing" on one device, then exporting, deleting, and re-importing. But maybe it will just happen again. It would be better to get to the bottom of this...)

**Comment by vincode-io** [comment] 2024-02-22 16:45
Honestly, I'm not sure what is happening. Once the outline gets fixed, the fix should propagate through iCloud to your other devices.

If you don't have any sensitive information in your corrupted Outline, could you use the Collaborate function to share it to me? Just email it to mo@vincode.io. I should be able to debug what the problem is and why the fix isn't propagating. The Collaborate function will let me see what is happening internally on the Outline which I can't see when looking at an OPML export of an Outline.

**Comment by vincode-io** [comment] 2024-02-22 22:29
I've been thinking a lot about your issue today. I _think_ I know why the corruption issue was ping-ponging between your devices. I made a small change to how the corruption correction code to see if it fixes your problem.

If you aren't already, please get TestFlight set up on at least one of your devices for Zavala.

https://testflight.apple.com/join/iFbND23m

When the 2.4 version is available in TestFlight, try fixing the corrupted outline on the device with the 2.4 TestFlight version installed. Force a sync on that device then switch to another device and force a sync on that one. Let me know if the second device still complains that the Outline is corrupted or not.

**Comment by vincode-io** [comment] 2024-02-23 17:41
The change I made should have fixed the scenario you describe. It should have pushed the row that was missing on your Mac to it from your iPhone.

1) Fixing on iPhone
2) Syncing on iPhone
3) Syncing on Mac
4) Opening on Mac

That order of events _should_ have fixed your problem, but it clearly didn't.

One thing you could try is to edit the row that comes back when fixing on the iPhone. Then try to sync and see what happens on your Mac after it syncs again. It should have forced that row to propagate to your Mac. You can undo the change after that.

I've been trying everything I can to recreate your corrupted outline, to no avail. Was this outline created on a pre-2.1 version of Zavala? The corruption might have been caused on older version with a syncing bug that wouldn't have been detected until later versions of Zavala when I put in the corruption check.

**Comment by vincode-io** [comment] 2024-02-24 02:05
You can try that. The other option would be to disable and reenable your Zavala iCloud Account on your Mac. That should make your Mac match exactly what is being stored currently in iCloud.

I'm at a loss to what is happening. I haven't had any luck at recreating your corrupted outline scenario no matter how hard I try. Right now I'm just shooting in the dark.

Are you offline a lot when editing your outlines? That is the hardest part about syncing outlines. I'm just curious if that is a contributing factor.

**Comment by vincode-io** [comment] 2024-02-24 03:35
@valleydali is there anything unusual about the row that won't sync? Does it have a lot of text in it or something?

**Comment by vincode-io** [comment] 2024-02-24 23:35
I think I figured out what caused the corruption and why your row won't sync. I _think_ that part of your Outline unloaded its data from memory while syncing that row. That would make it appear to the syncing system that the row was deleted and the syncing system deleted that row from iCloud.

The row was really still there on your iPhone when loading next time though. Unfortunately now that the row was deleted from iCloud, iCloud would no longer accept updates for it. That prevented it from propagating to your Mac when fixing the Outline corruption.

I've fixed the code so that it isn't possible for a partially loaded outline to be accessed while syncing which should prevent this kind of corruption from happening again. I need to test it some more, but I'll be releasing it soon to TestFlight. Hopefully not long after that, I'll do a production release.

You will need to delete and recreate the row in question on your iPhone. I'm sorry about that, but it is the most expedient way to get your outline straightened out.

Thank you for your patience with me on this. These kind of iCloud syncing problems are really hard to find and figure out. As it is, I have no way of being 100% sure that my hypothesis about what happened is correct. If I'm wrong, I'll take another go at it.

**Comment by vincode-io** [comment] 2024-02-26 00:49
I found another way this could have happened. Deleting a row and then using Undo to bring it back was buggy. The reconstituted row wouldn't sync, thus causing outlines to be corrupt on machines that would never receive the row. That has been fixed in the latest 2.4 beta.

**Comment by vincode-io** [comment] 2024-02-26 00:51
Because I have 2 different fixes in the upcoming 2.4 release that address this issue, I'll be closing it out. If you find anything either while testing 2.4 or using 2.4 after it is released, we can reopen this issue.

**Closed as completed by vincode-io** 2024-02-26 00:51 UTC
