### ISSUE TITLE
Copy As Markdown - Second Look & Notes list context menu listing [feature request]

### ISSUE THREAD

**Issue by pramjan90** [vincode-io/Zavala#180] opened 2022-07-22 18:56 UTC
Is there any chance of reviving this feature in the current version of the app? It certainly would be very handy to copy as markdown. as @brentsimmons points out, markdown to outline is diffucult, but I think most users would agree that is of secondary importance in this case.
Since we have export to markdown, can't we have copy to markdown?

Regards,
Pramod.

_Originally posted by @pramjan90 in https://github.com/vincode-io/Zavala/issues/6#issuecomment-1192852797_

**Comment by pramjan90** [comment] 2022-07-22 19:04
Also, for the copy function, is there any chance of including the tags and reference links?

Cheers!

**Comment by vincode-io** [comment] 2022-07-24 21:53
Duplicate of #6.

@pramjan90, the copy function works at the row level. Not the outline level. Tags and reference links are an outline property, not a row property. There wouldn't be anything to include in a copy function.

We could add tags and reference links to the Markdown export of an outline if there was a standard to do so.  Some Markdown editors and readers use YAML front matter, but there is no formal standard and it is only used in a few applications. Using YAML front matter may break Markdown editors/readers that don't recognize it. It is better to just not support it. You could write a Shortcut that does add it to an exported Markdown outline. I just can't include it in the main app.

**Closed by vincode-io** 2022-07-24 21:53 UTC
